### ISSUE TITLE
[Vulkan Loader] vkGetSwapchainImageKHR Invalid behavior

### ISSUE THREAD

**Issue by Nielsbishere** [googlesamples/vulkan-basic-samples#24] opened 2018-11-27 12:49 UTC
I don't know if this is the correct place to put Vulkan Loader issues for Android, but I was [recommended](https://github.com/KhronosGroup/Vulkan-Loader/issues/105) to post this issue to Google's Android Vulkan Loader.

On Android (s7 edge; Android 8.0; API lvl 24, arm64-v8a, build env windows-x86_64) the swapchain capabilities are minImageCount 2 and maxImageCount 3, however, when creating a swapchain with 3 buffers, vkGetSwapchainImageKHR returns 4.

```cpp
    Log::println(String("Option: ") + buffering);

    swapchainInfo.sType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR;
    swapchainInfo.minImageCount = buffering;
    swapchainInfo.clipped = VK_TRUE;
    swapchainInfo.imageExtent.width = size.x;
    swapchainInfo.imageExtent.height = size.y;
    swapchainInfo.imageFormat = ext.colorFormat;
    swapchainInfo.imageColorSpace = ext.colorSpace;
    swapchainInfo.surface = ext.surface;
    swapchainInfo.imageArrayLayers = 1;
    swapchainInfo.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
    swapchainInfo.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
    swapchainInfo.preTransform = VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR;
    swapchainInfo.compositeAlpha = (VkCompositeAlphaFlagBitsKHR) capabilities.supportedCompositeAlpha;
    swapchainInfo.presentMode = mode;

    vkCheck<0x9>(vkCreateSwapchainKHR(ext.device, &swapchainInfo, vkAllocator, &ext.swapchain), "Couldn't create swapchain");
    vkName(ext, ext.swapchain, VK_OBJECT_TYPE_SWAPCHAIN_KHR, "Back buffer swapchain");

    vkGetSwapchainImagesKHR(ext.device, ext.swapchain, &buffering, nullptr);

    Log::println(String("Successfully created swapchain (with buffering option ") + buffering + ")");
```

Input 'buffering' as 3 on Android and it returns 4; input 2 and it returns 3. While on Windows it works correctly and creates the correct buffers.

More implementation details can be found at my [branch](https://github.com/OsomiLunar/ocore/blob/versioning/ogc/src/graphics/gl/vulkan/vkgraphics.cpp) at Graphics::begin (line 575) and Graphics::end (line 601).

Is this a driver bug or is it invalid implementation? Is there a way I can detect if this behavior happens (so I can automatically reduce the back buffers), this results into present KHR to take up so much time, because it is using 4 buffers.

**Comment by zzyiwei** [comment] 2018-11-28 20:01
What is the number you get from "adb shell dumpsys SurfaceFlinger | grep NUM_FRAMEBUFFER_SURFACE_BUFFERS"?

**Comment by Nielsbishere** [comment] 2018-11-28 21:36
It says 3; so I assume that means it should use 3 max?

**Comment by cnorthrop** [comment] 2018-11-28 21:52
I believe this is expected behavior, not invalid.  Adding @ianelliottus if he can add more.

**Comment by Nielsbishere** [comment] 2018-11-28 22:15
It seems a bit odd that if I request 2 or 3 buffers I end up with 3 or 4; while the swapchain min/max buffers doesn't allow for more than 3 buffers. It really harms performance, most time is spent on presenting the image.

**Comment by zzyiwei** [comment] 2018-11-28 22:16
Yes, this is intended behavior as @cnorthrop said.
The calculation behind is:

number of swapchain images created = VkSwapchainCreateInfoKHR::minImage - 1 + minUndequeuedBuffers

minUndequeuedBuffers = (SurfaceFlinger::maxFrameBufferAcquiredBuffers - 1) + (async or nonblock mode ? 1 : 0)

You are probably not using async/nonblockDequeueBuffer mode, so that's why I'm asking NUM_FRAMEBUFFER_SURFACE_BUFFERS which is SurfaceFlinger::maxFrameBufferAcquiredBuffers.

Then number of swapchain images created = 3 - 1 + (3 - 1) = 4 which is working as intended.

The minImageCount 2 and maxImageCount 3 from the surface capability only restrict the number of images you could request but not the actual number of images allocated internally I think.

**Comment by zzyiwei** [comment] 2018-11-28 22:18
To add a little more here.

SurfaceFlinger::maxFrameBufferAcquiredBuffers is a ConfigStore value which is default to 2 but could be overwritten for each different device configuration.

**Comment by Nielsbishere** [comment] 2018-11-28 22:22
Does that mean that when I request 3 and it uses 4 internally, I have to version everything 3 or 4 times? Because currently it uses the output from vkGetSwapchainImagesKHR to determine how many times things have to be versioned. I assumed that whatever vkGetSwapchainImagesKHR returns is what options vkAcquireNextImageKHR can have (0-3), or is that not necessarily the case?

**Comment by chrisforbes** [comment] 2018-11-28 22:29
>  I assumed that whatever vkGetSwapchainImagesKHR returns is what options vkAcquireNextImageKHR can have (0-3), or is that not necessarily the case?

This is true.

> It really harms performance

The number of swapchain images should /not/ have a strong impact on performance beyond 3 images. 2 behaves very differently from 3, but 4+ should be almost identical to 3, only more wasteful of memory.

If you're seeing strange performance behavior, we should investigate that separately...

**Comment by chrisforbes** [comment] 2018-11-28 22:30
You may need to version /some/ things 4 times with a 4-image swapchain, but it shouldn't be everything. There will be 4 swapchain VkImageViews, and so 4 VkFramebuffers; what else you need to version depends on your strategy for recording command buffers.

**Comment by Nielsbishere** [comment] 2018-11-28 22:49
Currently, I just push out frames into the frame index returned by acquire next image and so I version all things that can be updated a frame 4 times. Before rendering this image, I wait for the fence for that frame index. Every image has a command buffer that it records. Is this recommended synchronization? I thought that because it seemed to return 4 swapchain images it might have something to do with that; because on Windows it always returns the amount you request. Are there any sources on Android-specific optimizations for synchronization?

**Comment by ggfan** [comment] 2021-04-29 05:11
closing down this one for now: if still a valid problem, feel free to re-open. In general, go to the upstream of the repo is recommended.

**Closed as completed by ggfan** 2021-04-29 05:11 UTC
